import {
  Home,
  Users,
  User,
  UserCheck,
  BookOpen,
  Book,
  FileText,
  FileCheck,
  ClipboardCheck,
  Calendar,
  MessageCircle,
  Bell,
} from 'lucide-react'

export const sidebarLinks = [
  { label: 'Home', route: '/admin', icon: Home },
  { label: 'Teachers', route: '/teachers', icon: Users },
  { label: 'Students', route: '/students', icon: User },
  { label: 'Parents', route: '/parents', icon: UserCheck },
  { label: 'Subjects', route: '/subjects', icon: BookOpen },
  { label: 'Classes', route: '/classes', icon: Book },
  { label: 'Lessons', route: '/lessons', icon: FileText },
  { label: 'Exams', route: '/exams', icon: FileCheck },
  { label: 'Assignments', route: '/assignments', icon: ClipboardCheck },
  { label: 'Results', route: '/results', icon: FileText },
  { label: 'Attendance', route: '/attendance', icon: Calendar },
  { label: 'Events', route: '/events', icon: Calendar },
  { label: 'Messages', route: '/messages', icon: MessageCircle },
  { label: 'Announcements', route: '/announcements', icon: Bell },
]
